name: Deploy Subgraph to Goldsky

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  deploy-subgraph:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Install pnpm
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      # Install Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      # Install dependencies using pnpm
      - name: Install dependencies
        run: pnpm install

      # Run codegen using pnpm
      - name: codegen
        run: pnpm run codegen

      # Build the project using pnpm
      - name: build
        run: pnpm run build

      # Set environment variable for SUBGRAPH_TAG based on event type
      - name: Set environment variable for SUBGRAPH_TAG
        if: github.event_name == 'pull_request'
        run: echo "SUBGRAPH_TAG=pr-${{ github.event.number }}" >> $GITHUB_ENV

      - name: Set SUBGRAPH_TAG to prod on merges to main
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: echo "SUBGRAPH_TAG=prod" >> $GITHUB_ENV

      # Install the Goldsky CLI
      - name: Install Goldsky CLI
        id: install-cli
        run: curl https://goldsky.com | sh -s -- -f
        shell: bash

      # Deploy subgraph using Goldsky CLI
      - name: Deploy Subgraph using Goldsky CLI
        id: deploy-subgraph
        run: goldsky subgraph deploy --token ${{ secrets.GOLDSKY_API_KEY }} ${{ env.SUBGRAPH_NAME }}/$SUBGRAPH_TAG --path .
        shell: bash