name: Deploy Subgraph to Goldsky

on:
  push:
    branches:
      - main

jobs:
  deploy-subgraph:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: codegen
        run: pnpm run codegen
      - name: build
        run: pnpm run build
      - name: Deploy Subgraph
        uses: goldsky-io/goldsky-deploy@latest
        with:
          api_key: ${{ secrets.GOLDSKY_API_KEY }}
          subgraph_name: 'ethereum-blocks'
          path: '.'
